 # SPDX-License-Identifier: MIT
 # Copyright (c) 2025, yasaisen (clover)
 # 
 # This file is part of a project licensed under the MIT License.
 # See the LICENSE file in the project root for more information.
 # 
 # last modified in 2506082358

model:
  weight_path: "/home/yasaisen/Desktop/27_research/research_main_v2/lab_07/weights"
  vit_model: "vit_base"
  # image_size: None
  freeze_vit: False
  cross_attention_freq: 4
  num_query_token: 32
  max_txt_len: 48
  embed_dim: 256
  drop_path_rate: 0
  use_grad_checkpoint: True

dataset:
  meta_path: "/home/yasaisen/Desktop/27_research/research_main_v2/lab_05/togit_v1/cleanPathVQAset_meta_2506060316.json"
  data_path: "/home/yasaisen/Desktop/27_research/research_datasets/cleanPCset_v1/quilt_1m/images"
  
  image_size: -1
  batch_size: 2
  bucket_size_multiplier: 50
  num_workers: 0
  pin_memory: True

task:
  # kd_teacher_name: "prov-gigapath"
  num_epoch: 12
  
  learning_rate: 1e-4
  weight_decay: 1e-2
  max_lr: 1e-3
  pct_start: 0.2
  anneal_strategy: "cos"
  device: "cuda"
  
  val_freq: 2
  save_freq: 2
  
env:
  root_path: ""
  
  world_size: 1
  distributed: True
  dist_url: 'env://'

  output_path: "outputs"
