 # SPDX-License-Identifier: MIT
 # Copyright (c) 2025, yasaisen (clover)
 # 
 # This file is part of a project licensed under the MIT License.
 # See the LICENSE file in the project root for more information.
 # 
 # last modified in 2506130458

model:
  weight_path: "/home/yasaisen/Desktop/27_research/research_main_v2/lab_07/weights"
  vit_model: "vit_base"
  freeze_vit: False
  cross_attention_freq: 4
  num_query_token: 32
  max_txt_len: 48
  embed_dim: 256
  drop_path_rate: 0
  use_grad_checkpoint: False # if KD do not turn on
  # image_size: None

dataset:
  meta_path: "/home/yasaisen/Desktop/27_research/research_main_v2/lab_05/togit_v1/cleanPathVQAset_meta_2506060316.json"
  data_path: "/home/yasaisen/Desktop/27_research/research_datasets/cleanPCset_v1/quilt_1m/images"
  croped_data: False
  
  multi_res_method: 'RatioPadInterp' # 'SimpleResize', 'RatioPadInterp', 'PatchPadBucket'
  
  image_size: 128
  size_ratio: 2
  new_img_height: 128
  pad_value: 1
  bucket_size_multiplier: 50
  
  test_data_num: 
    train: 16
    valid: 16
  batch_size: 2
  num_workers: 0
  pin_memory: True

task:
  kd_teacher_name: "H-optimus-0" # 'NoDistill', 'prov-gigapath', 'H-optimus-0'
  num_epoch: 12
  
  learning_rate: 1e-4
  weight_decay: 1e-2
  device: "cuda"
  
  val_freq: 2
  save_freq: 2
  
env:
  root_path: ""
  
  world_size: 1
  distributed: True
  dist_url: 'env://'

  output_path: "outputs"
